name = "orange-community"
main = "worker_cf.py"
compatibility_date = "2026-09-05"
compatibility_flags = [
  "python_workers"
]

[build]
command = "pip install -r requirements.txt"

[[d1_databases]]
binding = "DB"
database_name = "orange-community"
database_id = "05800bf1-0e28-4678-9a85-e9d9eec28039"

[vars]
CF_WORKER = "1"