name = "orange-community"
main = "main.py"
compatibility_date = "2026-09-06"
compatibility_flags = [
  "python_workers"
]

[[d1_databases]]
binding = "DB"
database_name = "orange-community"
database_id = "05800bf1-0e28-4678-9a85-e9d9eec28039"

[vars]
CF_WORKER = "1"